### ISSUE TITLE
question: commands to run under ubuntu

### ISSUE THREAD

**Issue by satfan52** [jhol/pyadf435x#4]
Hello, 
I have tested this tool in the past and I know it used to work. But for some reasons I can't make it work in my environment (latest version of Ubuntu 16.04). I have installed everything as per the installation instructions, including the firmware compilation and installation, but it does not seems to work:

Please advise on the right commands to use.
Please find below some debuging info

Thanks for your help
Regards
Peter

root@on7yi-ubuntu:/usr/src/pyadf435x# lsusb
Bus 001 Device 005: ID 0456:b403 Analog Devices, Inc

root@on7yi-ubuntu:/usr/src/pyadf435x# cycfx2prog run
No unconfigured Cypress FX2 attached.

root@on7yi-ubuntu:/usr/src/pyadf435x#  ./adf435xctl --freq 1000
Traceback (most recent call last):
  File "./adf435xctl", line 72, in <module>
    intf = getattr(adf435x.interfaces, args['interface'])()
  File "/usr/src/pyadf435x/adf435x/interfaces.py", line 27, in __init__
    raise ValueError('Device not found')
ValueError: Device not found

**Comment by 8urnside** [comment]
the code in interface.py is expecting 
idVendor=0x0456, idProduct=0xb40d

your device has product ID of b403. Just amend this line in interfaces.py to fix it.
